version: '3.8'

services:
  # Serviço do app Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slim_app
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./server/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - "DB_HOST=db"
      - "REDIS_HOST=cache"
    depends_on:
      - db
      - cache

  # Serviço Nginx
  webserver:
    image: nginx:alpine
    container_name: nginx_slim_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx
    depends_on:
      - app

  # Serviço MySQL
  db:
    image: mysql:8.3
    container_name: mysql_slim_app
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: slimdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: slim_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Serviço Redis
  cache:
    image: redis:alpine
    container_name: redis_slim_cache
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
  nginx_logs:
